Repository elastic/elasticsearch-hadoop, pull requests merged in 2020-05, with the labels that each got.

#1467 Bump 7.x to 7.9.0
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.8.0

#1468 [DOCS] Add 6.8.9 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.9.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, non-issue, v6.8.9

#1471 Upgrade to Gradle 6.4
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
  qa/kerberos/build.gradle
  spark/sql-13/build.gradle
  spark/sql-20/build.gradle
Labels: :Build, enhancement

#1451 Update references to latest stable, 7.7.0
  README.md
Labels: non-issue, v8.0.0

#1464 Bump 7.7 to 7.7.1
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.7.0

#1477 Share serialized settings and mappings between partition definitions
  mr/src/main/java/org/elasticsearch/hadoop/rest/PartitionDefinition.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/FindPartitionsTest.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/PartitionDefinitionTest.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/RestServiceTest.java
Labels: :Core, bug
