Repository elastic/elasticsearch-hadoop, pull requests merged in 2020-10, with the labels that each got.

#1537 Upgrade Gradle to version 6.6
  gradle/wrapper/gradle-wrapper.properties
Labels: :Build, enhancement

#1538 [7.x] Upgrade Gradle to version 6.6 (#1537)
  gradle/wrapper/gradle-wrapper.properties
Labels: backport

#1540 Bump 7.x to 7.11.0
  README.md
  buildSrc/esh-version.properties
Labels: non-issue

#1546 [DOCS] Add 6.8.13 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.13.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.13

#1545 [DOCS] Add 7.9.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.0, v7.11, v7.9.3, v8.0.0

#1547 [7.x] [DOCS] Add 7.9.3 release notes (#1545)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.11

#1548 [7.10] [DOCS] Add 7.9.3 release notes (#1545)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.10.0

#1549 [7.9] [DOCS] Add 7.9.3 release notes (#1545)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.9.3

#1544 Update Gradle wrapper to 6.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: :Build

#1542 Bump version for 7.9.3 release
  README.md
  buildSrc/esh-version.properties
Labels: non-issue
