Repository elastic/elasticsearch-hadoop, pull requests merged in 2020-09, with the labels that each got.

#1522 Remove references to the field-types docs section.
  docs/src/reference/asciidoc/core/mapping.adoc
  docs/src/reference/asciidoc/core/mr.adoc
Labels: >docs, v7.10.0, v7.9.0, v8.0.0

#1523 bump version after 7.9.1 release
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.9.1

#1524 Bump version in readme on master to 7.9.1
  README.md
Labels: non-issue, v7.9.1

#1526 [DOCS] Add 7.9.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.9.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.0, v7.9.2, v8.0.0

#1532 [master] [DOCS] Add 7.9.2 release notes (#1526)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1533 [7.x] [DOCS] Add 7.9.2 release notes (#1526)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.10.0

#1536 Bump latest version in README to 7.9.2
  README.md
Labels: non-issue, v7.9.2

#1535 Bump version for 7.9.2 release
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.9.2
