Repository elastic/elasticsearch-hadoop, pull requests merged in 2020-08, with the labels that each got.

#1509 Remove Travis configuration
  .travis.yml
Labels: :Build, non-issue

#1510 [7.x] Remove Travis configuration (#1509)
  .travis.yml
Labels: backport

#1511 [7.9] Remove Travis configuration (#1509)
  .travis.yml
Labels: backport

#1512 [6.8] Remove Travis configuration (#1509)
  .travis.yml
Labels: backport

#1513 [DOCS] Add 6.8.12 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.12.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.12

#1515 [DOCS] Add 7.9.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.9.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.0, v7.9.0, v8.0.0

#1516 [7.x] [DOCS] Add 7.9.0 release notes (#1515)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.0

#1517 [7.9] [DOCS] Add 7.9.0 release notes (#1515)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.9.1

#1514 Bump version to 6.8.13
  README.md
  buildSrc/esh-version.properties
Labels: v6.8.13

#1518 [DOCS] Add 7.9.1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.9.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.0, v7.9.1, v8.0.0

#1519 [7.x] [DOCS] Add 7.9.1 release notes (#1518)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.10.0

#1520 [7.9] [DOCS] Add 7.9.1 release notes (#1518)
  docs/src/reference/asciidoc/appendix/release-notes/7.9.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.9.1
