Repository elastic/elasticsearch-hadoop, pull requests merged in 2020-11, with the labels that each got.

#1552 Fix attempt to apply property to task collection
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/ElasticsearchFixturePlugin.groovy
Labels: v7.11

#1553 [DOCS] Add 7.10.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.10.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.0, v7.11

#1554 [7.10] [DOCS] Add 7.10.0 release notes (#1553)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.10.0

#1556 Bump 7.10.0 to 7.10.1
  README.md
  buildSrc/esh-version.properties
Labels: non-issue

#1555 Update references to latest stable, 7.10.0
  README.md
Labels: non-issue

#1559 [master] [DOCS] Add 7.10.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.10.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0
