Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-03, with the labels that each got.

#1613 New Data Tiers role support
  mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/NodeInfo.java
Labels: :Core, bug

#1615 [7.x] New Data Tiers role support (#1613)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/NodeInfo.java
Labels: backport

#1616 [7.12] New Data Tiers role support (#1613)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/NodeInfo.java
Labels: backport

#1611 [DOCS] Add 7.11.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.11.2, v7.12.0, v7.13.0, v8.0.0

#1618 [master] [DOCS] Add 7.11.2 release notes (#1611)
  docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1619 [7.x] [DOCS] Add 7.11.2 release notes (#1611)
  docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.13.0

#1620 [7.12] [DOCS] Add 7.11.2 release notes (#1611)
  docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.12.0

#1621 [7.11] Bump version for 7.11.2
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.11.2

#1623 [DOCS] Add 6.8.15 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.15.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.15

#1610 [DOCS] Add 7.12.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.12.0, v7.13.0, v8.0.0

#1624 [master] [DOCS] Add 7.12.0 release notes (#1610)
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1625 [7.x] [DOCS] Add 7.12.0 release notes (#1610)
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.13.0

#1626 [DOCS] Remove 6.8.15 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/6.8.15.adoc
Labels: >docs, v6.8.15

#1627 [DOCS] Remove 7.12.0 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
Labels: >docs, v7.12.0, v7.13.0, v8.0.0

#1628 [master] [DOCS] Remove 7.12.0 coming tag (#1627)
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
Labels: backport, v8.0.0

#1629 [7.x] [DOCS] Remove 7.12.0 coming tag (#1627)
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
Labels: backport, v7.12.0

#1632 [DOCS] Update breaking changes
  docs/src/reference/asciidoc/appendix/breaking.adoc
Labels: >docs, v7.12.0
