Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-05, with the labels that each got.

#1661 Fix test cluster wiring for integTests
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/StandaloneRestIntegTestTask.java
Labels: :Build

#1663 [DOCS] Add 6.8.16 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.16.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.16

#1662 [DOCS] Add 7.13.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.13.0, v7.14.0, v8.0.0

#1665 [master] [DOCS] Add 7.13.0 release notes (#1662)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1666 [7.x] [DOCS] Add 7.13.0 release notes (#1662)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.14.0

#1668 [DOCS] Remove 7.13.0 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
Labels: >docs, v7.13.0, v7.14.0, v8.0.0

#1670 [master] [DOCS] Remove 7.13.0 coming tag (#1668)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
Labels: backport

#1671 [7.x] [DOCS] Remove 7.13.0 coming tag (#1668)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
Labels: backport

#1667 [DOCS] Remove 6.8.16 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/6.8.16.adoc
Labels: >docs, v6.8.16

#1674 [master] [DOCS] Remove 7.12.1 coming tag (#1648)
  docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
Labels: backport, v8.0.0

#1673 [DOCS] Add 7.13.1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.13.1, v7.14.0, v8.0.0

#1675 [master] [DOCS] Add 7.13.1 release notes (#1673)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1676 [7.x] [DOCS] Add 7.13.1 release notes (#1673)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.14.0
