Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-11, with the labels that each got.

#1786 Release notes for 8.0.0-beta1
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs

#1788 [DOCS] Release notes for 8.0.0-beta1 (#1786)
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0, v8.0.0-beta1

#1794 Getting rid of gradle deprecation warnings (#1792)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  gradle/wrapper/gradle-wrapper.properties
  test/fixtures/minikdc/build.gradle
Labels: backport, v7.16.0

#1795 Getting rid of gradle deprecation warnings (#1792)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  gradle/wrapper/gradle-wrapper.properties
  test/fixtures/minikdc/build.gradle
Labels: backport, v8.0.0

#1783 Fix script update tests in Spark
  spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
Labels: bug, :Testing, v8.0.0, v8.1.0

#1796 [8.0] Fix script update tests in Spark (#1783)
  spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
Labels: backport

#1797 Backing up gradle to a version that works with scala 2.10
  gradle/wrapper/gradle-wrapper.properties
Labels: v8.0.0, v7.16.0, v7.16.1, v8.1.0

#1798 Backing up gradle to a version that works with scala 2.10 (#1797)
  gradle/wrapper/gradle-wrapper.properties
Labels: backport, v8.0.0

#1799 Backing up gradle to a version that works with scala 2.10 (#1797)
  gradle/wrapper/gradle-wrapper.properties
Labels: backport, v7.16.0, v7.16.1

#1800 Setting java boot classpath so that scala 2.10 works on gradle 7.2
  gradle/wrapper/gradle-wrapper.properties
  spark/core/build.gradle
  spark/sql-13/build.gradle
  spark/sql-20/build.gradle
  spark/sql-30/build.gradle
Labels: discuss

#1790 [DOCS] Remove coming tag from 8.0.0-beta1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc
Labels: v8.0.0, v8.0.0-beta1

#1787 [8.x] [DOCS] Remove coming tag from 8.0.0-beta1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-beta1.adoc
Labels: >docs, v8.0.0-beta1, v8.1.0

#1804 [DOCS] Add 7.15.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.15.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.15.2

#1805 [7.16] [DOCS] Add 7.15.2 release notes (#1804)
  docs/src/reference/asciidoc/appendix/release-notes/7.15.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.16.0
