Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-09, with the labels that each got.

#1740 [DOCS] Add 7.14.1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.15.0, v7.14.1, v7.16.1

#1743 [DOCS] Remove coming tag from 7.14.1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
Labels: >docs, v7.14.1

#1741 Bump version after 7.14.1 release
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.14.1

#1742 Updated stable release version after 7.14.1 release.
  README.md
Labels: >docs, v7.15.0, v8.0.0, v7.16.0

#1744 Using case-insensitive headers
  mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
Labels: bug, :Rest

#1749 [7.x] [DOCS] Add 7.14.1 release notes (#1740)
  docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1750 [7.15] [DOCS] Add 7.14.1 release notes (#1740)
  docs/src/reference/asciidoc/appendix/release-notes/7.14.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1753 [DOCS] Add release notes for 8.0.0-alpha2
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.0.0-alpha2

#1757 [DOCS] Add 7.14.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.14.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: v7.15.0, v8.0.0, v7.16.0, v7.14.2

#1759 [7.15] [DOCS] Add 7.14.2 release notes (#1757)
  docs/src/reference/asciidoc/appendix/release-notes/7.14.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: v7.15.0

#1764 [DOCS] Add 6.8.19 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.19.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.19

#1765 Version bump for 7.14.2
  README.md
  buildSrc/esh-version.properties
Labels: non-issue, v7.14.2

#1766 Version bump for 7.14.2
  README.md
Labels: non-issue, v8.0.0

#1767 [DOCS] Add 7.15.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.15.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.15.0, v7.16.1

#1768 [7.x] [DOCS] Add 7.15.0 release notes (#1767)
  docs/src/reference/asciidoc/appendix/release-notes/7.15.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.16.0
