Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-06, with the labels that each got.

#1678 Fix spring io repository usage
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
Labels: :Build

#1677 [DOCS] Remove 7.13.1 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
Labels: >docs, v7.13.1, v7.14.0, v8.0.0

#1680 [master] [DOCS] Remove 7.13.1 coming tag (#1677)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
Labels: backport, v8.0.0

#1681 [7.x] [DOCS] Remove 7.13.1 coming tag (#1677)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
Labels: backport, v7.14.0

#1684 Remove the conjars repository from the build
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
Labels: :Build, enhancement

#1687 [DOCS] Add 7.13.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.13.2, v7.14.0, v8.0.0

#1689 [7.x] [DOCS] Add 7.13.2 release notes (#1687)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.14.0

#1683 Fix failing strict wildcard pushdown tests
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: :Spark, :Testing, bug

#1691 [7.x] Fix failing strict wildcard pushdown tests (#1683)
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: backport

#1692 [7.13] Fix failing strict wildcard pushdown tests (#1683)
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: backport

#1690 [DOCS] Remove 7.13.2 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
Labels: >docs, v7.13.2, v7.14.0, v8.0.0

#1693 [master] [DOCS] Remove 7.13.2 coming tag (#1690)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
Labels: backport, v8.0.0

#1694 [7.x] [DOCS] Remove 7.13.2 coming tag (#1690)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
Labels: backport, v7.14.0

#1686 Remove problem dependency
  hive/build.gradle
Labels: :Build, bug

#1679 Verify cluster main info response returns correct product headers
  mr/src/main/java/org/elasticsearch/hadoop/handler/impl/elasticsearch/ElasticsearchHandler.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java
  mr/src/main/java/org/elasticsearch/hadoop/util/EsMajorVersion.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
  mr/src/test/java/org/elasticsearch/hadoop/util/EsMajorVersionTest.java
Labels: :Core, :Rest, enhancement

#1696 [7.x] Verify cluster main info response returns correct product headers (#1679)
  mr/src/main/java/org/elasticsearch/hadoop/handler/impl/elasticsearch/ElasticsearchHandler.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/Response.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/SimpleResponse.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/commonshttp/CommonsHttpTransport.java
  mr/src/main/java/org/elasticsearch/hadoop/util/EsMajorVersion.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/RestClientTest.java
  mr/src/test/java/org/elasticsearch/hadoop/util/EsMajorVersionTest.java
Labels: backport

#1700 [DOCS] Update ES glossary references
  docs/src/reference/asciidoc/core/arch.adoc
  docs/src/reference/asciidoc/core/mr.adoc
Labels: >docs, v7.13.3, v7.14.0, v8.0.0

#1701 [7.x] [DOCS] Update ES glossary references (#1700)
  docs/src/reference/asciidoc/core/arch.adoc
  docs/src/reference/asciidoc/core/mr.adoc
Labels: backport, v7.14.0

#1702 [7.13] [DOCS] Update ES glossary references (#1700)
  docs/src/reference/asciidoc/core/arch.adoc
  docs/src/reference/asciidoc/core/mr.adoc
Labels: backport, v7.13.3
