Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-01, with the labels that each got.

#1568 [DOCS] Add 7.10.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.10.2, v7.11, v7.12.0, v8.0.0

#1570 [master] [DOCS] Add 7.10.2 release notes (#1568)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1571 [7.x] [DOCS] Add 7.10.2 release notes (#1568)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.12.0

#1572 [7.11] [DOCS] Add 7.10.2 release notes (#1568)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.11.1

#1569 [DOCS] Add 7.11.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.11, v7.12.0, v8.0.0

#1575 [7.x] [DOCS] Add 7.11.0 release notes (#1569)
  docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.12.0

#1574 [master] [DOCS] Add 7.11.0 release notes (#1569)
  docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1576 [DOCS] Add 6.8.14 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.14.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.14

#1578 Update Gradle wrapper to version 6.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: :Build, v8.0.0

#1573 [DOCS] Remove 7.10.2 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
Labels: >docs, v7.10.2, v7.11.1, v7.12.0, v8.0.0

#1580 [master] [DOCS] Remove 7.10.2 coming tag (#1573)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
Labels: backport, v8.0.0

#1581 [7.x] [DOCS] Remove 7.10.2 coming tag (#1573)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
Labels: backport, v7.12.0

#1582 [7.11] [DOCS] Remove 7.10.2 coming tag (#1573)
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
Labels: backport, v7.11.1

#1583 Version bump to 7.10.3
  README.md
  buildSrc/esh-version.properties
Labels: :Build

#1584 Add properties for pulling java versions from the environment variables
  gradle.properties
Labels: :Build, bug

#1585 [7.x] Add properties for pulling java versions from the environment variables (#1584)
  gradle.properties
Labels: backport

#1586 Distinguish core Spark artifacts from each other
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
  spark/core/build.gradle
Labels: :Build, :Spark, bug

#1587 [7.x] Distinguish core Spark artifacts from each other (#1586)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
  spark/core/build.gradle
Labels: backport

#1588 [7.11] Distinguish core Spark artifacts from each other (#1586)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/scala/SparkVariantPlugin.java
  spark/core/build.gradle
Labels: backport

#1589 Add support for Spark integration on Scala 2.12
  licenses/scala-library-2.11.12.jar.sha1
  licenses/scala-library-2.12.8.jar.sha1
  licenses/scala-reflect-2.11.12.jar.sha1
  licenses/scala-reflect-2.12.8.jar.sha1
  licenses/spark-catalyst_2.11-2.4.4.jar.sha1
  licenses/spark-catalyst_2.12-2.4.4.jar.sha1
  licenses/spark-core_2.11-2.4.4.jar.sha1
  licenses/spark-core_2.12-2.4.4.jar.sha1
  licenses/spark-sql_2.11-2.4.4.jar.sha1
  licenses/spark-sql_2.12-2.4.4.jar.sha1
  licenses/spark-streaming_2.11-2.4.4.jar.sha1
  licenses/spark-streaming_2.12-2.4.4.jar.sha1
  licenses/spark-yarn_2.11-2.4.4.jar.sha1
  licenses/spark-yarn_2.12-2.4.4.jar.sha1
  spark/core/build.gradle
  spark/core/licenses/scala-library-2.11.12.jar.sha1
  spark/core/licenses/scala-library-2.12.8.jar.sha1
  spark/core/licenses/scala-reflect-2.11.12.jar.sha1
  spark/core/licenses/scala-reflect-2.12.8.jar.sha1
  spark/core/licenses/spark-core_2.11-2.4.4.jar.sha1
  spark/core/licenses/spark-core_2.12-2.4.4.jar.sha1
  spark/core/src/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
  spark/sql-20/build.gradle
  spark/sql-20/licenses/scala-library-2.11.12.jar.sha1
  spark/sql-20/licenses/scala-library-2.12.8.jar.sha1
  spark/sql-20/licenses/scala-reflect-2.11.12.jar.sha1
  spark/sql-20/licenses/scala-reflect-2.12.8.jar.sha1
  spark/sql-20/licenses/spark-catalyst_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-catalyst_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-core_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-core_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-sql_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-sql_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-streaming_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-streaming_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-yarn_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-yarn_2.12-2.4.4.jar.sha1
Labels: :Build, :Spark, enhancement

#1591 [7.x] Add support for Spark integration on Scala 2.12 (#1589)
  licenses/scala-library-2.11.12.jar.sha1
  licenses/scala-library-2.12.8.jar.sha1
  licenses/scala-reflect-2.11.12.jar.sha1
  licenses/scala-reflect-2.12.8.jar.sha1
  licenses/spark-catalyst_2.11-2.4.4.jar.sha1
  licenses/spark-catalyst_2.12-2.4.4.jar.sha1
  licenses/spark-core_2.11-2.4.4.jar.sha1
  licenses/spark-core_2.12-2.4.4.jar.sha1
  licenses/spark-sql_2.11-2.4.4.jar.sha1
  licenses/spark-sql_2.12-2.4.4.jar.sha1
  licenses/spark-streaming_2.11-2.4.4.jar.sha1
  licenses/spark-streaming_2.12-2.4.4.jar.sha1
  licenses/spark-yarn_2.11-2.4.4.jar.sha1
  licenses/spark-yarn_2.12-2.4.4.jar.sha1
  spark/core/build.gradle
  spark/core/licenses/scala-library-2.11.12.jar.sha1
  spark/core/licenses/scala-library-2.12.8.jar.sha1
  spark/core/licenses/scala-reflect-2.11.12.jar.sha1
  spark/core/licenses/scala-reflect-2.12.8.jar.sha1
  spark/core/licenses/spark-core_2.11-2.4.4.jar.sha1
  spark/core/licenses/spark-core_2.12-2.4.4.jar.sha1
  spark/core/src/main/scala/org/elasticsearch/spark/rdd/EsRDDWriter.scala
  spark/sql-20/build.gradle
  spark/sql-20/licenses/scala-library-2.11.12.jar.sha1
  spark/sql-20/licenses/scala-library-2.12.8.jar.sha1
  spark/sql-20/licenses/scala-reflect-2.11.12.jar.sha1
  spark/sql-20/licenses/scala-reflect-2.12.8.jar.sha1
  spark/sql-20/licenses/spark-catalyst_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-catalyst_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-core_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-core_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-sql_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-sql_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-streaming_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-streaming_2.12-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-yarn_2.11-2.4.4.jar.sha1
  spark/sql-20/licenses/spark-yarn_2.12-2.4.4.jar.sha1
Labels: backport
