Repository elastic/elasticsearch-hadoop, pull requests merged in 2021-07, with the labels that each got.

#1706 Bump 7.x branch to 7.15
  README.md
  buildSrc/esh-version.properties
Labels: non-issue

#1707 [DOCS] Added RNs for 7.13.3
  docs/src/reference/asciidoc/appendix/release-notes/7.13.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.13.3

#1709 7.13
  docs/src/reference/asciidoc/appendix/release-notes/7.13.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.13.3

#1708 6.8
  docs/src/reference/asciidoc/appendix/release-notes/6.8.17.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.17

#1710 7.14
  docs/src/reference/asciidoc/appendix/release-notes/7.13.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, backport

#1711 [master] [DOCS] Added RNs for 7.13.3 (#1707)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1705 Fix buildSrc classpath after build-tools refactoring
  buildSrc/build.gradle
Labels: :Build

#1715 [7.x] Fix buildSrc classpath after build-tools refactoring (#1705)
  buildSrc/build.gradle
Labels: backport

#1716 [7.14] Fix buildSrc classpath after build-tools refactoring (#1705)
  buildSrc/build.gradle
Labels: backport

#1717 [DOCS] Add 7.13.4 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.13.4, v7.14.1, v7.15.0, v8.0.0

#1718 [master] [DOCS] Add 7.13.4 release notes (#1717)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0

#1719 [7.x] [DOCS] Add 7.13.4 release notes (#1717)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.15.0

#1720 [7.14] [DOCS] Add 7.13.4 release notes (#1717)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.14.0

#1721 [DOCS] Remove 7.13.4 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
Labels: >docs, v7.13.4, v7.14.1, v7.15.0, v8.0.0

#1722 [master] [DOCS] Remove 7.13.4 coming tag (#1721)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
Labels: backport

#1724 [7.14] [DOCS] Remove 7.13.4 coming tag (#1721)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
Labels: backport, v7.14.0

#1723 [7.x] [DOCS] Remove 7.13.4 coming tag (#1721)
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
Labels: backport, v7.15.0

#1726 [DOCS] Add breaking changes + RNs for 8.0.0-alpha1
  docs/src/reference/asciidoc/appendix/breaking.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.0-alpha1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.0-alpha2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.0-beta1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.0-rc1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.0-rc2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.0.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.1.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.1.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.10.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.10.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.10.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.11.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.11.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.11.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.12.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.12.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.13.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.13.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.13.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.13.3.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.13.4.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.2.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.2.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.3.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.3.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.3.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.4.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.5.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.5.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.5.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.6.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.6.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.6.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.7.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.7.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.8.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.8.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.9.0.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.9.1.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.9.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/7.9.3.adoc
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.0.0
