Repository elastic/elasticsearch-hadoop, pull requests merged in 2022-05, with the labels that each got.

#1955 [DOCS] Add missing 8.1.2 and 8.1.3 release notes in 8.2
  docs/src/reference/asciidoc/appendix/release-notes/8.1.2.adoc
  docs/src/reference/asciidoc/appendix/release-notes/8.1.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1956 [DOCS] Add 8.2.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.2.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.2.0, v8.3.0

#1957 [8.2][DOCS] Add 8.2.0 release notes (#1956)
  docs/src/reference/asciidoc/appendix/release-notes/8.2.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1961 [DOCS] Add 7.17.4 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.17.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.4

#1960 [DOCS] Add 8.2.1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.2.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.3.0, v8.2.1

#1962 [8.2] [DOCS] Add 8.2.1 release notes (#1960)
  docs/src/reference/asciidoc/appendix/release-notes/8.2.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1964 [8.2] [DOCS] Add 8.2.2 release notes (#1963)
  docs/src/reference/asciidoc/appendix/release-notes/8.2.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1965 [8.3] [DOCS] Add 8.2.2 release notes (#1963)
  docs/src/reference/asciidoc/appendix/release-notes/8.2.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport
