Repository elastic/elasticsearch-hadoop, pull requests merged in 2022-01, with the labels that each got.

#1846 [DOCS] Remove PR #1350 from 8.0.0-alpha1 RNs
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
Labels: >docs, v8.0.0-alpha1, v8.1.0

#1847 [8.0] [DOCS] Remove PR 1350 from 8.0.0-alpha1 RNs (#1846)
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-alpha1.adoc
Labels: v8.0.0-alpha1, backport

#1848 [DOCS] Add 7.16.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.0, v7.16.3

#1478 resolve saveToEs saves case classes fields with NULL values #998
  mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/FilteringValueWriter.java
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
  spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
Labels: bug, v8.0.0, v8.1.0, v7.17.0

#1849 [DOCS] Add 6.8.23 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.23.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v6.8.23

#1850 [7.17] [DOCS] Add 7.16.3 release notes (#1848)
  docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v7.17.0

#1853 resolve saveToEs saves case classes fields with NULL values #998 (#1478)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/FilteringValueWriter.java
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
  spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
Labels: backport, v8.0.0

#1854 resolve saveToEs saves case classes fields with NULL values #998 (#1478)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/FilteringValueWriter.java
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
  spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
Labels: backport, v7.17.0

#1855 Fixing a scala compilation problem
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
  spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
Labels: non-issue, v8.0.0, v8.1.0, v7.17.0

#1856 Fixing a scala compilation problem (#1855)
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
  spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
Labels: non-issue, backport, v8.0.0

#1857 Fixing a scala compilation problem (#1855)
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueWriter.scala
  spark/core/src/test/scala/org/elasticsearch/spark/serialization/ScalaValueWriterTest.scala
Labels: non-issue, backport, v7.17.0

#1823 Adding support for wildcard fields
  mr/src/main/java/org/elasticsearch/hadoop/serialization/FieldType.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/MappingTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typed/primitives.json
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaValueReader.scala
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
Labels: feature, v8.1.0

#1827 Fixing support for empty and null arrays
  mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/mapping.json
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/scroll.json
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: bug, v8.0.0, v8.1.0, v7.17.0

#1858 Fixing a unit test failure
  mr/src/test/java/org/elasticsearch/hadoop/serialization/dto/mapping/MappingTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/dto/mapping/typeless/primitives.json
Labels: non-issue, v8.1.0

#1859 [DOCS] Add 8.0.0-rc1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.1.0, v8.0.0-rc1

#1860 [8.0] [DOCS] Add 8.0.0-rc1 release notes (#1859)
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, auto-merge

#1861 [DOCS] Remove 8.0.0-rc1 coming tag
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
Labels: >docs, v8.1.0, v8.0.0-rc1

#1862 [master] [DOCS] Remove 8.0.0-rc1 coming tag (#1861)
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
Labels: backport, auto-merge

#1863 [DOCS] Add missing items to 8.0.0-rc1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
Labels: >docs, v8.1.0, v8.0.0-rc1

#1864 [master] [DOCS] Add missing items to 8.0.0-rc1 release notes (#1863)
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc1.adoc
Labels: backport, v8.1.0, auto-merge

#1851 [DOCS] Remove coming tag from 6.8.23 release notes
  docs/src/reference/asciidoc/appendix/release-notes/6.8.23.adoc
Labels: >docs, v6.8.23

#1852 [DOCS] Remove coming tag from 7.16.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc
Labels: >docs, v7.17.0, v7.16.3

#1868 Getting rid of direct cross-project dependencies to avoid gradle warnings
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  qa/kerberos/build.gradle
Labels: :Build, v8.0.0, v8.1.0

#1869 Getting rid of direct cross-project dependencies to avoid gradle warnings (#1868)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  qa/kerberos/build.gradle
Labels: backport, v8.0.0

#1867 [7.17] [DOCS] Remove coming tag from 7.16.3 release notes (#1852)
  docs/src/reference/asciidoc/appendix/release-notes/7.16.3.adoc
Labels: backport, auto-merge

#1873 Check for invalid characters in X-Opaque-ID headers
  mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
  mr/src/test/java/org/elasticsearch/hadoop/cfg/SettingsTest.java
Labels: bug, v8.0.0, v8.1.0, v7.17.0

#1874 Check for invalid characters in X-Opaque-ID headers (#1873)
  mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
  mr/src/test/java/org/elasticsearch/hadoop/cfg/SettingsTest.java
Labels: backport, v8.0.0

#1875 Check for invalid characters in X-Opaque-ID headers (#1873)
  mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
  mr/src/test/java/org/elasticsearch/hadoop/cfg/SettingsTest.java
Labels: backport, v7.17.0

#1839 Adding support for update output mode to structured streaming
  mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/sql/streaming/StreamingQueryTestHarness.scala
  spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/sql/streaming/StreamingQueryTestHarness.scala
  spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
Labels: feature, v8.1.0

#1841 Supporting scala 2.13 for spark 3.2.0
  gradle.properties
  spark/core/build.gradle
  spark/core/src/main/scala/org/elasticsearch/spark/rdd/AbstractEsRDD.scala
  spark/core/src/main/scala/org/elasticsearch/spark/rdd/JDKCollectionConvertersCompat.scala
  spark/core/src/main/scala/org/elasticsearch/spark/serialization/ScalaMapFieldExtractor.scala
  spark/sql-13/build.gradle
  spark/sql-20/build.gradle
  spark/sql-30/build.gradle
  spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
  spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/SchemaUtils.scala
Labels: feature, v8.1.0

#1838 Adding support for upserts of nested arrays
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala
  spark/sql-13/src/test/scala/org/elasticsearch/spark/sql/DataFrameValueWriterTest.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala
  spark/sql-20/src/test/scala/org/elasticsearch/spark/sql/DataFrameValueWriterTest.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DataFrameValueWriter.scala
  spark/sql-30/src/test/scala/org/elasticsearch/spark/sql/DataFrameValueWriterTest.scala
Labels: bug, v8.1.0

#1845 Deprecating old technology
  docs/src/reference/asciidoc/appendix/breaking.adoc
  docs/src/reference/asciidoc/core/intro/requirements.adoc
  mr/src/main/java/org/elasticsearch/hadoop/mr/EsInputFormat.java
  pig/src/main/java/org/elasticsearch/hadoop/pig/EsStorage.java
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/package.scala
  spark/sql-13/src/main/scala/org/elasticsearch/spark/streaming/EsSparkStreaming.scala
  storm/src/main/java/org/elasticsearch/storm/EsBolt.java
  storm/src/main/java/org/elasticsearch/storm/EsSpout.java
Labels: deprecation, >docs, v8.0.0, v8.1.0

#1876 Deprecating old technology (#1845)
  docs/src/reference/asciidoc/appendix/breaking.adoc
  docs/src/reference/asciidoc/core/intro/requirements.adoc
  mr/src/main/java/org/elasticsearch/hadoop/mr/EsInputFormat.java
  pig/src/main/java/org/elasticsearch/hadoop/pig/EsStorage.java
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/EsSparkSQL.scala
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/package.scala
  spark/sql-13/src/main/scala/org/elasticsearch/spark/streaming/EsSparkStreaming.scala
  storm/src/main/java/org/elasticsearch/storm/EsBolt.java
  storm/src/main/java/org/elasticsearch/storm/EsSpout.java
Labels: deprecation, backport, v8.0.0

#1878 Expected exception when incorrectly configuring upsert has changed
  mr/src/itest/java/org/elasticsearch/hadoop/integration/mr/AbstractMROldApiSaveTest.java
Labels: non-issue, v8.1.0

#1880 Fixing scala 2.13 problems in integration tests
  spark/core/src/itest/java/org/elasticsearch/spark/integration/AbstractHadoopBasicSparkTest.java
  spark/core/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkTest.java
  spark/core/src/itest/java/org/elasticsearch/spark/integration/ScalaUtils.java
  spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
  spark/core/src/main/scala/org/elasticsearch/spark/rdd/JDKCollectionConvertersCompat.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
  spark/sql-30/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkSQLTest.java
  spark/sql-30/src/itest/java/org/elasticsearch/spark/integration/AbstractJavaEsSparkStreamingTest.java
  spark/sql-30/src/itest/java/org/elasticsearch/spark/integration/ScalaUtils.java
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractJavaEsSparkStructuredStreamingTest.java
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsScalaSparkStreaming.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkStructuredStreaming.scala
  spark/sql-30/src/test/scala/org/elasticsearch/spark/sql/RowSerializationEventConverterTest.scala
Labels: non-issue

#1840 Fixing docsReceived counter
  mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
Labels: bug, v8.0.0, v8.1.0, v7.17.0

#1844 Fixing out of date requirements docs
  docs/src/reference/asciidoc/core/intro/requirements.adoc
  docs/src/reference/asciidoc/index.adoc
Labels: bug, >docs, v8.0.0, v8.1.0, v7.17.0

#1842 Avoiding failure when using frozen indices
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/no-scroll-id/scroll.json
Labels: bug, v8.0.0, v8.1.0, v7.17.0

#1883 Fixing out of date requirements docs (#1844)
  docs/src/reference/asciidoc/core/intro/requirements.adoc
  docs/src/reference/asciidoc/index.adoc
Labels: backport, v8.0.0

#1884 Fixing out of date requirements docs (#1844)
  docs/src/reference/asciidoc/core/intro/requirements.adoc
  docs/src/reference/asciidoc/index.adoc
Labels: backport, v7.17.0

#1881 Fixing docsReceived counter (#1840)
  mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
Labels: backport, v8.0.0

#1882 Fixing docsReceived counter (#1840)
  mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
Labels: backport, v7.17.0

#1885 Avoiding failure when using frozen indices (#1842)
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/no-scroll-id/scroll.json
Labels: backport, v8.0.0

#1886 Avoiding failure when using frozen indices (#1842)
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestRepository.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/ScrollQuery.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
  mr/src/test/java/org/elasticsearch/hadoop/rest/ScrollQueryTest.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/no-scroll-id/scroll.json
Labels: backport, v7.17.0

#1888 Fixing ScrollReaderTest compilation
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
Labels: non-issue, v7.17.0

#1887 Fixing ScrollReaderTest compilation
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
Labels: non-issue, v8.0.0

#1454 add scripted upsert feature
  mr/src/main/java/org/elasticsearch/hadoop/cfg/ConfigurationOptions.java
  mr/src/main/java/org/elasticsearch/hadoop/cfg/Settings.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/JsonScriptTemplateBulk.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/ScriptTemplateBulk.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/UpdateBulkFactory.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/CommandTest.java
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: feature, :Core, discuss, v8.1.0

#1889 Fixing support for empty and null arrays (#1827)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/mapping.json
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/scroll.json
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: backport, v8.0.0

#1891 [DOCS] Add 7.17.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.17.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.0

#1892 [DOCS] Add 8.0.0-rc2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.0.0-rc2, v8.1.0

#1893 [8.0] [DOCS] Add 8.0.0-rc2 release notes (#1892)
  docs/src/reference/asciidoc/appendix/release-notes/8.0.0-rc2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport, v8.0.0-rc2

#1890 Fixing support for empty and null arrays (#1827)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java
  mr/src/test/java/org/elasticsearch/hadoop/serialization/ScrollReaderTest.java
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/mapping.json
  mr/src/test/resources/org/elasticsearch/hadoop/serialization/scrollReaderTestData/empty-list/scroll.json
  spark/sql-13/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSparkSQL.scala
Labels: backport, v7.17.0

#1870 Checking result of bulk writes
  mr/src/main/java/org/elasticsearch/hadoop/serialization/bulk/AbstractBulkFactory.java
Labels: bug, :Core, v8.1.0
