Repository elastic/elasticsearch-hadoop, pull requests merged in 2022-04, with the labels that each got.

#1944 Updating the Hadoop fixture version to 3.3.2
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/HadoopServiceDescriptor.groovy
Labels: non-issue, backport pending, v8.2.0, v7.17.3, 8.3.0

#1945 Updating hadoop fixture version to 3.3.2 (#1944)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/HadoopServiceDescriptor.groovy
Labels: backport, v8.2.0

#1943 Fixing DST bug in data_nanos support
  mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
Labels: bug, :Core, 8.3.0

#1948 Fixing DST bug in data_nanos support (#1943)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
Labels: backport, auto-merge, v7.17.3

#1947 Fixing DST bug in data_nanos support (#1943)
  mr/src/main/java/org/elasticsearch/hadoop/serialization/builder/JdkValueWriter.java
Labels: backport, auto-merge, v8.2.0

#1952 [DOCS] Add 7.17.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.17.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.3

#1951 [DOCS] Add 8.1.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.1.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.2.0, v8.1.3

#1953 [8.1] [DOCS] Add 8.1.3 release notes (#1951)
  docs/src/reference/asciidoc/appendix/release-notes/8.1.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#1950 Backport java 17 build support to 7.17
  .ci/java-versions.properties
  hive/build.gradle
  pig/build.gradle
  spark/core/build.gradle
  spark/sql-13/build.gradle
  spark/sql-20/build.gradle
  spark/sql-30/build.gradle
  test/shared/build.gradle
Labels: :Build, backport, v7.17.4
