Repository elastic/elasticsearch-hadoop, pull requests merged in 2022-09, with the labels that each got.

#1997 Ignoring missing indices if es.index.read.missing.as.empty is true
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestClient.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
  spark/core/src/itest/scala/org/elasticsearch/spark/integration/AbstractScalaEsSpark.scala
Labels: bug, :Rest, v8.5.0

#1998 [DOCS] Add 8.4.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.4.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.5.0, v8.4.2

#1999 [8.4] [DOCS] Add 8.4.2 release notes (#1998)
  docs/src/reference/asciidoc/appendix/release-notes/8.4.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2000 Update index.adoc
  docs/src/reference/asciidoc/index.adoc
Labels: v5.0.2, v5.2.0, v5.1.1, v5.5.0, v5.4.1, v5.3.3, v7.0.0, v6.0.1, v6.1.2, v6.2.3, v6.3.2, v6.5.0, v5.6.13, v6.4.3, v6.6.0, >docs, v6.7.0, v7.1.1, v7.2.1, v7.3.2, v7.4.1, v7.5.2, v7.6.3, v7.7.1, v7.8.1, v7.9.3, v7.10.3, v7.11.3, v7.12.2, v7.13.5, v7.14.3, v7.15.3, v7.16.4, v6.8.24, v8.0.2, v8.1.4, v8.2.4, v7.17.6, v8.3.4, v8.4.3

#2002 [8.4] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2004 [8.2] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2001 [8.5] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2005 [8.1] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2006 [8.0] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2007 [7.17] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2008 [7.16] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2009 [7.15] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2011 [7.13] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2012 [7.12] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2013 [7.11] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2014 [7.10] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2015 [7.9] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2016 [7.8] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2017 [7.7] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2018 [7.6] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2019 [7.5] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2020 [7.4] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2024 [7.3] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2021 [7.2] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2022 [7.1] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2023 [7.0] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport

#2025 [6.8] Update index.adoc (#2000)
  docs/src/reference/asciidoc/index.adoc
Labels: backport
