Repository elastic/elasticsearch-hadoop, pull requests merged in 2023-12, with the labels that each got.

#2168 Update gradle wrapper to 8.5
  gradle/wrapper/gradle-wrapper.properties
Labels: non-issue, :Build, backport pending, auto-merge, v8.12.0, v8.11.2

#2173 [8.11] Update gradle wrapper to 8.5 (#2168)
  gradle/wrapper/gradle-wrapper.properties
Labels: :Build, backport, v8.11.2

#2174 [7.17] Fix Gradle 8 deprecation warnings (#2071)
  build.gradle
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/ConcatFilesTask.java
  dist/build.gradle
Labels: non-issue, :Build, auto-merge

#2175 [7.17] Update Gradle wrapper to 8.1 (#2077)
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: non-issue, :Build

#2181 [8.11] [DOCS] Add 8.11.2 release notes (#2180)
  docs/src/reference/asciidoc/appendix/release-notes/8.11.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2182 [8.12] [DOCS] Add 8.11.2 release notes (#2180)
  docs/src/reference/asciidoc/appendix/release-notes/8.11.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2184 [DOCS] Add 7.17.16 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.17.16.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.17

#2183 [DOCS] Add 8.11.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.11.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.11.3, v8.12.1, v8.13.0

#2186 [8.12] [DOCS] Add 8.11.3 release notes (#2183)
  docs/src/reference/asciidoc/appendix/release-notes/8.11.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2185 [8.11] [DOCS] Add 8.11.3 release notes (#2183)
  docs/src/reference/asciidoc/appendix/release-notes/8.11.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport
