Repository elastic/elasticsearch-hadoop, pull requests merged in 2023-04, with the labels that each got.

#2075 FIxing WritableBytesConverter to not overwrite bytes with wrong value
  mr/src/main/java/org/elasticsearch/hadoop/mr/SafeWritableConverter.java
  mr/src/main/java/org/elasticsearch/hadoop/mr/WritableBytesConverter.java
  mr/src/test/java/org/elasticsearch/hadoop/mr/WritableBytesConverterTests.java
Labels: bug, :Hive, v8.8.0

#2083 Update to Spark 3.2.4
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/SparkYarnServiceDescriptor.groovy
  gradle.properties
  licenses/spark-catalyst_2.12-3.2.3.jar.sha1
  licenses/spark-catalyst_2.12-3.2.4.jar.sha1
  licenses/spark-core_2.12-3.2.3.jar.sha1
  licenses/spark-core_2.12-3.2.4.jar.sha1
  licenses/spark-sql_2.12-3.2.3.jar.sha1
  licenses/spark-sql_2.12-3.2.4.jar.sha1
  licenses/spark-streaming_2.12-3.2.3.jar.sha1
  licenses/spark-streaming_2.12-3.2.4.jar.sha1
  licenses/spark-yarn_2.12-3.2.3.jar.sha1
  licenses/spark-yarn_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-catalyst_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-catalyst_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-core_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-core_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-sql_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-sql_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-streaming_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-streaming_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-yarn_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-yarn_2.12-3.2.4.jar.sha1
Labels: :Spark, non-issue, :Build

#2086 [8.8] Update to Spark 3.2.4 (#2083)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/SparkYarnServiceDescriptor.groovy
  gradle.properties
  licenses/spark-catalyst_2.12-3.2.3.jar.sha1
  licenses/spark-catalyst_2.12-3.2.4.jar.sha1
  licenses/spark-core_2.12-3.2.3.jar.sha1
  licenses/spark-core_2.12-3.2.4.jar.sha1
  licenses/spark-sql_2.12-3.2.3.jar.sha1
  licenses/spark-sql_2.12-3.2.4.jar.sha1
  licenses/spark-streaming_2.12-3.2.3.jar.sha1
  licenses/spark-streaming_2.12-3.2.4.jar.sha1
  licenses/spark-yarn_2.12-3.2.3.jar.sha1
  licenses/spark-yarn_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-catalyst_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-catalyst_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-core_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-core_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-sql_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-sql_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-streaming_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-streaming_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-yarn_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-yarn_2.12-3.2.4.jar.sha1
Labels: backport

#2087 [8.7] Update to Spark 3.2.4 (#2083)
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/fixture/hadoop/services/SparkYarnServiceDescriptor.groovy
  gradle.properties
  licenses/spark-catalyst_2.12-3.2.3.jar.sha1
  licenses/spark-catalyst_2.12-3.2.4.jar.sha1
  licenses/spark-core_2.12-3.2.3.jar.sha1
  licenses/spark-core_2.12-3.2.4.jar.sha1
  licenses/spark-sql_2.12-3.2.3.jar.sha1
  licenses/spark-sql_2.12-3.2.4.jar.sha1
  licenses/spark-streaming_2.12-3.2.3.jar.sha1
  licenses/spark-streaming_2.12-3.2.4.jar.sha1
  licenses/spark-yarn_2.12-3.2.3.jar.sha1
  licenses/spark-yarn_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-catalyst_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-catalyst_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-core_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-core_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-sql_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-sql_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-streaming_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-streaming_2.12-3.2.4.jar.sha1
  spark/sql-30/licenses/spark-yarn_2.12-3.2.3.jar.sha1
  spark/sql-30/licenses/spark-yarn_2.12-3.2.4.jar.sha1
Labels: backport
