Repository elastic/elasticsearch-hadoop, pull requests merged in 2023-05, with the labels that each got.

#2085 [DOCS] Add 7.17.10 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.17.10.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.10

#2084 [DOCS] Add 8.7.1 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.7.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.7.1, v8.8.1

#2089 [8.8] [DOCS] Add 8.7.1 release notes (#2084)
  docs/src/reference/asciidoc/appendix/release-notes/8.7.1.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2080 Replacing the use of Java object serialization with Jackson
  mr/src/main/java/org/elasticsearch/hadoop/rest/PartitionDefinition.java
  mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/mapping/Field.java
  mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/mapping/Mapping.java
  mr/src/main/java/org/elasticsearch/hadoop/util/IOUtils.java
  mr/src/main/java/org/elasticsearch/hadoop/util/SettingsUtils.java
  mr/src/test/java/org/elasticsearch/hadoop/util/IOUtilsTest.java
  pig/src/main/java/org/elasticsearch/hadoop/pig/EsStorage.java
  pig/src/test/java/org/elasticsearch/hadoop/pig/PigSchemaSaveTest.java
  spark/sql-13/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
  spark/sql-20/src/itest/scala/org/elasticsearch/spark/sql/streaming/StreamingQueryTestHarness.scala
  spark/sql-20/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
  spark/sql-30/src/itest/scala/org/elasticsearch/spark/sql/streaming/StreamingQueryTestHarness.scala
  spark/sql-30/src/main/scala/org/elasticsearch/spark/sql/DefaultSource.scala
  test/shared/src/main/java/org/elasticsearch/hadoop/util/TestUtils.java
Labels: bug, :Core, v8.9.0

#2091 [8.7] Fix DRA build by removing Gradle 8 deprecation warnings #2071
  build.gradle
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BuildPlugin.groovy
  buildSrc/src/main/java/org/elasticsearch/hadoop/gradle/buildtools/ConcatFilesTask.java
  dist/build.gradle
Labels: backport

#2094 [8.8] [DOCS] Add 8.8.0 release notes (#2093)
  docs/src/reference/asciidoc/appendix/release-notes/8.8.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport
