Repository elastic/elasticsearch-hadoop, pull requests merged in 2024-07, with the labels that each got.

#2217 Clean up Spark dependency lists
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/BaseBuildPlugin.groovy
  licenses/protobuf-java-2.5.0.jar.sha1
  licenses/protobuf-java-LICENSE.txt
  licenses/protobuf-java-NOTICE.txt
  spark/core/build.gradle
  spark/sql-20/build.gradle
  spark/sql-20/licenses/protobuf-java-2.5.0.jar.sha1
  spark/sql-20/licenses/protobuf-java-LICENSE.txt
  spark/sql-20/licenses/protobuf-java-NOTICE.txt
  spark/sql-30/build.gradle
  spark/sql-30/licenses/protobuf-java-2.5.0.jar.sha1
  spark/sql-30/licenses/protobuf-java-LICENSE.txt
  spark/sql-30/licenses/protobuf-java-NOTICE.txt
Labels: enhancement, :Build, v8.15.0

#2242 [DOCS] Add 8.14.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.14.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.15.0, v8.14.3

#2243 [8.14] [DOCS] Add 8.14.2 release notes (#2242)
  docs/src/reference/asciidoc/appendix/release-notes/8.14.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2245 [DOCS] Add 8.14.3 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.14.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.15.1, v8.16.0, v8.14.4

#2246 [8.15] [DOCS] Add 8.14.3 release notes (#2245)
  docs/src/reference/asciidoc/appendix/release-notes/8.14.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2247 [8.14] [DOCS] Add 8.14.3 release notes (#2245)
  docs/src/reference/asciidoc/appendix/release-notes/8.14.3.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2248 Update Gradle wrapper to 8.9
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: v7.17.23, v8.15.1, v8.16.0, v8.14.4
