Repository elastic/elasticsearch-hadoop, pull requests merged in 2024-12, with the labels that each got.

#2297 [DOCS] Add 8.17.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.17.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v9.0.0, v8.17.1, v8.18.0

#2299 [8.x] [DOCS] Add 8.17.0 release notes (#2297)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2298 [8.17] [DOCS] Add 8.17.0 release notes (#2297)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2300 [DOCS] Add 7.17.26 release notes
  docs/src/reference/asciidoc/appendix/release-notes/7.17.26.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v7.17.27

#2301 [DOCS] Add 8.16.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v9.0.0, v8.17.1, v8.18.0, v8.16.3

#2304 [8.x] [DOCS] Add 8.16.2 release notes (#2301)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2303 [8.17] [DOCS] Add 8.16.2 release notes (#2301)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2302 [8.16] [DOCS] Add 8.16.2 release notes (#2301)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2307 Add Gradle enterprise setup
  .buildkite/hooks/pre-command
  build.gradle
  buildSrc/src/main/groovy/org/elasticsearch/hadoop/gradle/util/CiUtils.groovy
  settings.gradle
Labels: non-issue
