Repository elastic/elasticsearch-hadoop, pull requests merged in 2024-08, with the labels that each got.

#2253 [DOCS] Add 8.15.0 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.15.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.15.1, v8.16.0

#2254 [8.15] [DOCS] Add 8.15.0 release notes (#2253)
  docs/src/reference/asciidoc/appendix/release-notes/8.15.0.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2255 Update Gradle wrapper to 8.10
  gradle/wrapper/gradle-wrapper.properties
Labels: auto-merge
