Repository elastic/elasticsearch-hadoop, pull requests merged in 2025-02, with the labels that each got.

#2337 [DOCS] Add 8.16.4 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.18.1, v8.19.0, v9.0.1, v9.1.0, v8.16.5, v8.17.3

#2338 [8.16] [DOCS] Add 8.16.4 release notes (#2337)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2339 [8.17] [DOCS] Add 8.16.4 release notes (#2337)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2340 [8.18] [DOCS] Add 8.16.4 release notes (#2337)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2341 [8.x] [DOCS] Add 8.16.4 release notes (#2337)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2342 [9.0] [DOCS] Add 8.16.4 release notes (#2337)
  docs/src/reference/asciidoc/appendix/release-notes/8.16.4.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2343 [DOCS] Add 8.17.2 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.18.1, v8.19.0, v9.0.1, v9.1.0, v8.17.3

#2344 [8.17] [DOCS] Add 8.17.2 release notes (#2343)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2345 [8.18] [DOCS] Add 8.17.2 release notes (#2343)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2346 [8.x] [DOCS] Add 8.17.2 release notes (#2343)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2347 [9.0] [DOCS] Add 8.17.2 release notes (#2343)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.2.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2348 [docs] Add the new docs CI checks
  .github/workflows/comment-on-asciidoc-changes.yml
  .github/workflows/docs-build.yml
  .github/workflows/docs-cleanup.yml
Labels: >docs
