Repository elastic/elasticsearch-hadoop, pull requests merged in 2025-04, with the labels that each got.

#2374 [DOCS] Add 8.17.5 release notes
  docs/src/reference/asciidoc/appendix/release-notes/8.17.4.adoc
  docs/src/reference/asciidoc/appendix/release-notes/8.17.5.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: >docs, v8.18.1, v8.19.0, v8.17.6

#2376 [8.18] [DOCS] Add 8.17.5 release notes (#2374)
  docs/src/reference/asciidoc/appendix/release-notes/8.17.4.adoc
  docs/src/reference/asciidoc/appendix/release-notes/8.17.5.adoc
  docs/src/reference/asciidoc/appendix/release.adoc
Labels: backport

#2373 [DOCS] Add 9.0.0 release notes
  docs/release-notes/breaking-changes.md
Labels: >docs, v9.0.1, v9.1.0

#2377 [9.0] [DOCS] Add 9.0.0 release notes (#2373)
  docs/release-notes/breaking-changes.md
Labels: backport

#2379 Cleaning up the README field
  README.md
Labels: >docs, auto-backport, v9.0.1, v9.1.0
